name: digit-detection
channels:
  - conda-forge
  - ioam
  - soumith
dependencies:
  - python=3.6
  - numpy
  - mkl
  - holoviews
  - jupyter
  - pandas
  - matplotlib
  - seaborn
  - pytorch
  - torchvision
  - pip:
    - flake8
    - tqdm
    - pillow
    - packaging
    - appdirs
    - holoviews
    - gpustat
    - sklearn
    - easydict
    - ipdb
