skopt: false
config_name: MultiLoss_Avenue
dataset_name: SVHN
seed: 1234
dataloader:
  train: true
  valid_split: 0.2
  sample_size: -1 # Set to ~1000 if debugging, -1 uses all the data 
  batch_size: 32
model:
  multiloss: true
  model: VGG19
  pretrained: true # If pretrained is specified, model is ignored
  pretrained_path: results/SVHN_Multiloss_test_b2_2019_03_18_13_52_28/checkpoint.pth
  num_classes: 7
optimizer:
  lr: 0.001
  momentum: 0.9
train:
  num_epochs: 25
  max_patience: 8
