skopt: True
config_name: 'TestMultiloss_skopt'
dataset_name: SVHN
seed: 1234

# Hyperparameters related to dataloader
dataloader:
  train: True
  valid_split: 0.2
  sample_size: 1000 # Number of samples to use (for debugging purposes), set to -1 to use the entire dataset
  batch_size: 32

# Hyperparameters of the model
model:
  model: 'MultiLoss'
  num_classes: 7


# Hyperparameters of the optimizer
optimizer:
  lr: 0.001
  momentum: 0.9  # does not work for now

# Hyperparameters related to model training
train:
  num_epochs: 25
